---

- name: eBGP session set-up NSO service
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yaml


#
#
#   THIS PLAYBOOK WILL NOT RUN WITHOUT THE "SESSION_NAME" VARIABLE PASSED AT RUNTIME
#
#   usage 'ansible-playbook ebgp-nso-destroy.yaml -e "session_name=foo"'
#
#

  tasks:

  - name: Run NSO eBGP service
    nso_config:
      url: '{{ url }}'
      username: '{{ username }}'
      password: '{{ password }}'
      data:
        ebgp:ebgp:
        - name: '{{ session_name }}'
          __state: absent

