---

- name: Setup BGP configs for CSR using ios_config module
  hosts: csr
  gather_facts: no


  vars_files:
    - vars.yaml


  tasks:


  - name: Configure loopback interface for CSR
    ios_config:
      lines:
        - no interface Loopback0


  - name: Configure BGP for CSR
    ios_config:
      lines:
        - no router bgp {{ target1.local_as }}




- name: Setup BGP configs for ISR using ios_config module
  hosts: isr
  gather_facts: no


  vars_files:
    - vars.yaml


  tasks:


  - name: Configure loopback interface for ISR
    ios_config:
      lines:
        - no interface Loopback0


  - name: Configure BGP for ISR
    ios_config:
      lines:
        - no router bgp {{ target2.local_as }}
